import { ThemedText } from '@/components/themed-text';
import { Colors, Spacing } from '@/constants/theme';
import { HYMNS } from '@/data/hymns';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StyleSheet, TextInput, View } from 'react-native';

export default function HymnsScreen() {
  const { category } = useLocalSearchParams<{ category?: string }>();
  const [query, setQuery] = useState('');
  const [sortDescending, setSortDescending] = useState(false);
  const hymns = useMemo(() => HYMNS.filter((hymn) => (!category || hymn.category === category) && `${hymn.number} ${hymn.title} ${hymn.alternateTitle ?? ''} ${hymn.verses.flatMap((verse) => verse.lines).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sortDescending ? b.number - a.number : a.number - b.number), [category, query, sortDescending]);
  return <SafeAreaView style={styles.safe}><FlatList data={hymns} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><ThemedText type="title">Hymns</ThemedText><ThemedText themeColor="textSecondary">{hymns.length} songs in the collection</ThemedText><TextInput value={query} onChangeText={setQuery} placeholder="Search lyrics, titles, or numbers" placeholderTextColor="#718096" style={styles.search} /><Pressable onPress={() => setSortDescending((value) => !value)} style={styles.sort}><ThemedText style={styles.sortText}>{sortDescending ? 'Highest numbers first' : 'Lowest numbers first'}</ThemedText></Pressable></View>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: '/hymn/[id]', params: { id: item.id } })} style={styles.row}><View style={styles.number}><ThemedText style={styles.numberText}>{String(item.number).padStart(2, '0')}</ThemedText></View><View style={styles.copy}><ThemedText type="subtitle">{item.title}</ThemedText><ThemedText themeColor="textSecondary" numberOfLines={1}>{item.alternateTitle ?? item.category}</ThemedText></View><ThemedText themeColor="textSecondary">-&gt;</ThemedText></Pressable>} ListEmptyComponent={<ThemedText style={styles.empty}>No hymns match that search.</ThemedText>} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.light.background }, content: { padding: Spacing.four, paddingBottom: 110, gap: Spacing.two, maxWidth: 760, width: '100%', alignSelf: 'center' }, header: { gap: Spacing.two, marginBottom: Spacing.two }, search: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e1e6ee', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, color: Colors.light.text, marginTop: Spacing.two }, sort: { alignSelf: 'flex-start', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 20, backgroundColor: '#e8eef9' }, sortText: { color: Colors.light.primary, fontWeight: '700', fontSize: 12 }, row: { flexDirection: 'row', alignItems: 'center', padding: Spacing.three, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e1e6ee', borderRadius: 16, gap: Spacing.three }, number: { width: 44, height: 44, borderRadius: 12, backgroundColor: Colors.light.backgroundElement, alignItems: 'center', justifyContent: 'center' }, numberText: { color: Colors.light.primary, fontWeight: '800' }, copy: { flex: 1, gap: 4 }, empty: { paddingVertical: Spacing.four, textAlign: 'center' } });