import { ThemedText } from '@/components/themed-text';
import { Colors, Spacing } from '@/constants/theme';
import { HYMNS } from '@/data/hymns';
import { Stack, router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, Share, StyleSheet, View } from 'react-native';

export default function HymnDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const hymn = useMemo(() => HYMNS.find((item) => item.id === id || String(item.number) === id), [id]);
  const [fontSize, setFontSize] = useState(18);
  if (!hymn) return <SafeAreaView style={styles.safe}><ThemedText style={styles.notFound}>Hymn not found.</ThemedText></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><Stack.Screen options={{ title: `Hymn ${hymn.number}`, headerBackTitle: 'Back' }} /><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><View><ThemedText style={styles.number}>HYMN {hymn.number}</ThemedText><ThemedText type="title" style={styles.title}>{hymn.title}</ThemedText><ThemedText themeColor="textSecondary">{hymn.alternateTitle ?? hymn.category}</ThemedText></View><Pressable onPress={() => Share.share({ message: `${hymn.title}\n${hymn.verses.flatMap((verse) => verse.lines).join('\n')}` })} style={styles.share}><ThemedText style={styles.shareText}>Share</ThemedText></Pressable></View><View style={styles.meta}><ThemedText>{hymn.category}</ThemedText>{hymn.tune && <ThemedText themeColor="textSecondary">Tune: {hymn.tune}</ThemedText>}{hymn.meter && <ThemedText themeColor="textSecondary">{hymn.meter}</ThemedText>}</View><View style={styles.controls}><ThemedText themeColor="textSecondary">Reading size</ThemedText><View style={styles.sizes}>{[16, 18, 22, 26].map((size) => <Pressable key={size} onPress={() => setFontSize(size)} style={[styles.size, fontSize === size && styles.selected]}><ThemedText style={fontSize === size ? styles.selectedText : undefined}>A</ThemedText></Pressable>)}</View></View>{hymn.verses.map((verse) => <View key={verse.number} style={styles.verse}><ThemedText style={styles.verseLabel}>VERSE {verse.number}</ThemedText>{verse.lines.map((line) => <ThemedText key={line} style={[styles.line, { fontSize, lineHeight: fontSize * 1.7 }]}>{line}</ThemedText>)}</View>)}{hymn.chorus && <View style={styles.chorus}><ThemedText style={styles.verseLabel}>CHORUS</ThemedText>{hymn.chorus.map((line) => <ThemedText key={line} style={[styles.line, { fontSize, lineHeight: fontSize * 1.7 }]}>{line}</ThemedText>)}</View>}<ThemedText style={styles.amen}>Amen.</ThemedText><Pressable onPress={() => router.push('/explore')} style={styles.back}><ThemedText style={styles.backText}>Return to hymns</ThemedText></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.light.background }, content: { padding: Spacing.four, paddingBottom: 100, maxWidth: 760, width: '100%', alignSelf: 'center' }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: Spacing.two }, number: { color: Colors.light.accent, fontWeight: '800', fontSize: 12, letterSpacing: 1 }, title: { marginTop: 6, fontSize: 32 }, share: { backgroundColor: Colors.light.primary, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 14 }, shareText: { color: '#fff', fontWeight: '700' }, meta: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two, paddingVertical: Spacing.three, borderBottomWidth: 1, borderBottomColor: '#dfe5ed' }, controls: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: Spacing.three }, sizes: { flexDirection: 'row', gap: 6 }, size: { width: 32, height: 32, borderRadius: 8, borderWidth: 1, borderColor: '#ccd5e2', alignItems: 'center', justifyContent: 'center' }, selected: { backgroundColor: Colors.light.primary, borderColor: Colors.light.primary }, selectedText: { color: '#fff' }, verse: { paddingVertical: Spacing.three, borderTopWidth: 1, borderTopColor: '#e7ebf0' }, chorus: { padding: Spacing.three, backgroundColor: '#f5f0dd', borderRadius: 14, marginTop: Spacing.two }, verseLabel: { color: Colors.light.accent, fontSize: 11, fontWeight: '800', letterSpacing: 1, marginBottom: 10 }, line: { fontFamily: 'serif', color: Colors.light.text }, amen: { textAlign: 'center', fontFamily: 'serif', fontSize: 20, fontStyle: 'italic', paddingVertical: Spacing.four }, back: { alignSelf: 'center', backgroundColor: Colors.light.gold, borderRadius: 12, padding: Spacing.three }, backText: { color: Colors.light.onGold, fontWeight: '800' }, notFound: { textAlign: 'center', marginTop: 80 } });